# Generated by Django 2.2.17 on 2021-01-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transactionpaymentgateway',
            table='TransactionPaymentGateway',
        ),
    ]
